FROM azul/zulu-openjdk-alpine:21
ENV AWS_END_POINT AWS_END_POINT
ENV AWS_SQS_ENDPOINT_ENVIA_EMAILS AWS_SQS_ENDPOINT_ENVIA_EMAILS
ENV AWS_ACCESS_KEY AWS_ACCESS_KEY
ENV AWS_SECRET_KEY AWS_SECRET_KEY
ENV AWS_REGION AWS_REGION
ENV AWS_QUEUE_NAME AWS_QUEUE_NAME
EXPOSE 8084
COPY target/*.jar entrega-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/entrega-0.0.1-SNAPSHOT.jar"]
