amazon:
    aws:
        accesskey: test-access-key
        secretkey: test-secret-key
        queueName: test-queuename-key
    dynamodb:
        endpoint: http://localhost:8000
        region: test-region
