package com.entrega.model.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.Data;

import java.util.List;


@DynamoDBTable(tableName = "db_entregas")
@Data
public class Entrega {

    private String id;
    private String idPedido;
    private Cliente cliente;
    private String dataPedido;
    private double totalPedido;
    private String formaPagamento;
    private String validadeFormaPagamentoCartao;
    private List<PedidoProduto> pedidoProdutos;
    private String status;



    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "idPedido")
    public String getIdPedido() {
        return idPedido;
    }

    public void setIdPedido(String idPedido) {
        this.idPedido = idPedido;
    }

    @DynamoDBAttribute(attributeName = "cliente")
    public Cliente getCliente() {
        return cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    @DynamoDBAttribute(attributeName = "dataPedido")
    public String getDataPedido() {
        return dataPedido;
    }

    public void setDataPedido(String dataPedido) {
        this.dataPedido = dataPedido;
    }
    @DynamoDBAttribute(attributeName = "totalPedido")
    public double getTotalPedido() {
        return totalPedido;
    }

    public void setTotalPedido(double totalPedido) {
        this.totalPedido = totalPedido;
    }
    @DynamoDBAttribute(attributeName = "formaPagamento")
    public String getFormaPagamento() {
        return formaPagamento;
    }

    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }
    @DynamoDBAttribute(attributeName = "validadeFormaPagamentoCartao")
    public String getValidadeFormaPagamentoCartao() {
        return validadeFormaPagamentoCartao;
    }

    public void setValidadeFormaPagamentoCartao(String validadeFormaPagamentoCartao) {
        this.validadeFormaPagamentoCartao = validadeFormaPagamentoCartao;
    }

    @DynamoDBAttribute(attributeName = "pedidoProdutos")
    public List<PedidoProduto> getPedidoProdutos() {
        return pedidoProdutos;
    }

    public void setPedidoProdutos(List<PedidoProduto> pedidoProdutos) {
        this.pedidoProdutos = pedidoProdutos;
    }
    @DynamoDBAttribute(attributeName = "status")
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}